apiVersion: v1
kind: Namespace
metadata:
  name: lw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lw-role
rules:
  - apiGroups:
      - webapp.cwall.club
    resources:
      - lwcontrollers
    verbs:
      - delete
      - get
      - list
      - watch
      - update
      - patch
      - create
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - delete
      - get
      - list
      - watch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lw-sa
  namespace: lw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lw-crb
  namespace: lw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lw-role
subjects:
  - kind: ServiceAccount
    name: lw-sa
    namespace: lw
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lw-controller
  namespace: lw
  labels:
    app: lw
spec:
  selector:
    matchLabels:
      app: lw
  template:
    metadata:
      labels:
        app: lw
    spec:
      serviceAccountName: lw-sa
      containers:
        - name: lw
          image: wucl627/lwcontroller:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30