# permissions for end users to view lwcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lwcontroller-viewer-role
rules:
- apiGroups:
  - webapp.cwall.club
  resources:
  - lwcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.cwall.club
  resources:
  - lwcontrollers/status
  verbs:
  - get
